---

- name: Check if telegraf is installed
  command: dpkg-query -W telegraf
  register: telegraf_check_deb
  failed_when: telegraf_check_deb.rc > 1
  changed_when: "(telegraf_check_deb.rc == 1) or (telegraf_version not in telegraf_check_deb.stdout) "

- name: Download telegraf
  include: 'download.yml'
  when: "(telegraf_check_deb.rc == 1) or (telegraf_version not in telegraf_check_deb.stdout)"

- name: Configure telegraf
  include: 'configure.yml'
